const ProductsData = [
    {
        pname:"White Comfy Stool",
        _pid:"01",
        pdetails: " write something about products",
        price:258.00,
        rating:3,
        review:100,
        slug:"Shirt",
        img:"/images/d1.png",
        stock:12,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"Wardrobe",
        sold:102,
        discout:"10%",
        cupon:"SalaGorib",
        shipping: 10
    },
    {
        pname:"Four Door Wardrobe",
        _pid:"02",
        pdetails: " write something about products",
        price:150.00,
        rating:4.5,
        review:100,
        slug:"Pant",
        img:"/images/d2.png",
        stock:33,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"sofa",
        sold:102,
        discout:"15%",
        cupon:"Gorib",
        shipping: 50
    },
    {
        pname:"Orange Classic Sofa",
        _pid:"03",
        pdetails: " write something about products",
        price:550.00,
        rating:2,
        review:100,
        slug:"Lunggi",
        img:"/images/d10.png",
        stock:0,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"sofa",
        sold:102,
        discout:"15%",
        cupon:"Gorib",
        shipping: 50
    },
    {
        pname:"Royal Ash Sofa",
        _pid:"04",
        pdetails: " write something about products",
        price:189.00,
        rating:5,
        review:100,
        slug:"MensShoe",
        img:"/images/d4.png",
        stock:24,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"stool",
        sold:102,
        discout:"15%",
        cupon:"Gorib",
        shipping: 50
    },
    {
        pname:"Royal Queen Black Chair",
        _pid:"05",
        pdetails: " write something about products",
        price:480.00,
        rating:3.5,
        review:100,
        slug:"Punjabi",
        img:"/images/d5.png",
        stock:1240,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"sofa",
        sold:102,
        discout:"10%",
        cupon:"SalaGorib",
        shipping: 50
    },
    {
        pname:"White Luxury Sofa",
        _pid:"06",
        pdetails: " write something about products",
        price:150.00,
        rating:1,
        review:100,
        slug:"Payjama",
        img:"/images/d6.png",
        stock:0,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"chair",
        sold:102,
        discout:"15%",
        cupon:"Gorib",
        shipping: 50
    },
    {
        pname:"Queen Black Chair",
        _pid:"07",
        pdetails: " write something about products",
        price:850.00,
        rating:0,
        review:100,
        slug:"Watch",
        img:"/images/d7.png",
        stock:48,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"sofa",
        sold:102,
        discout:"15%",
        cupon:"Fokinni",
        shipping: 50
    },
    {
        pname:"Wooden Yellow Comfort",
        _pid:"08",
        pdetails: " write something about products",
        price:350.00,
        rating:5,
        review:100,
        slug:"Tshirt",
        img:"/images/d8.png",
        stock:96,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"sofa",
        sold:102,
        discout:"15%",
        cupon:"Gorib",
        shipping: 50
    },
    {
        pname:"Luxury Sofa",
        _pid:"09",
        pdetails: "write something about products",
        price:750.00,
        rating:4.5,
        review:100,
        slug:"PoloShirt",
        img:"/images/d5.png",
        stock:124,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"chair",
        sold:102,
        discout:"15%",
        cupon:"Fokinni",
        shipping: 50
    },

    {
        pname:"White Comfy Stool",
        _pid:"10",
        pdetails: " write something about products",
        price:258.00,
        rating:3,
        review:100,
        slug:"Shirt",
        img:"/images/d1.png",
        stock:12,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"Wardrobe",
        sold:102,
        discout:"10%",
        cupon:"SalaGorib",
        shipping: 50
    },
    {
        pname:"Four Door Wardrobe",
        _pid:"11",
        pdetails: " write something about products",
        price:150.00,
        rating:4.5,
        review:100,
        slug:"Pant",
        img:"/images/d2.png",
        stock:33,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"sofa",
        sold:102,
        discout:"15%",
        cupon:"Gorib",
        shipping: 50
    },
    {
        pname:"Orange Classic Sofa",
        _pid:"12",
        pdetails: " write something about products",
        price:550.00,
        rating:2,
        review:100,
        slug:"Lunggi",
        img:"/images/d10.png",
        stock:0,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"sofa",
        sold:102,
        discout:"15%",
        cupon:"Gorib",
        shipping: 50
    },
    {
        pname:"Royal Ash Sofa",
        _pid:"13",
        pdetails: " write something about products",
        price:189.00,
        rating:5,
        review:100,
        slug:"MensShoe",
        img:"/images/d4.png",
        stock:24,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"stool",
        sold:102,
        discout:"15%",
        cupon:"Gorib",
        shipping: 50
    },
    {
        pname:"Royal Queen Black Chair",
        _pid:"14",
        pdetails: " write something about products",
        price:480.00,
        rating:3.5,
        review:100,
        slug:"Punjabi",
        img:"/images/d5.png",
        stock:1240,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"sofa",
        sold:102,
        discout:"10%",
        cupon:"SalaGorib",
        shipping: 50
    },
    {
        pname:"White Luxury Sofa",
        _pid:"15",
        pdetails: " write something about products",
        price:150.00,
        rating:1,
        review:100,
        slug:"Payjama",
        img:"/images/d6.png",
        stock:0,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"chair",
        sold:102,
        discout:"15%",
        cupon:"Gorib",
        shipping: 50
    },
    {
        pname:"Queen Black Chair",
        _pid:"16",
        pdetails: " write something about products",
        price:850.00,
        rating:0,
        review:100,
        slug:"Watch",
        img:"/images/d7.png",
        stock:48,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"sofa",
        sold:102,
        discout:"15%",
        cupon:"Fokinni",
        shipping: 50
    },
    {
        pname:"Wooden Yellow Comfort",
        _pid:"17",
        pdetails: " write something about products",
        price:350.00,
        rating:5,
        review:100,
        slug:"Tshirt",
        img:"/images/d8.png",
        stock:96,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"sofa",
        sold:102,
        discout:"15%",
        cupon:"Gorib",
        shipping: 50
    },
    {
        pname:"Luxury Sofa",
        _pid:"18",
        pdetails: "write something about products",
        price:750.00,
        rating:4.5,
        review:100,
        slug:"PoloShirt",
        img:"/images/d5.png",
        stock:124,
        description:"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown",
        category:"chair",
        sold:102,
        discout:"15%",
        cupon:"Fokinni",
        shipping: 50
    },




]

export default ProductsData